"""Immutable evaluation seed splits.

Phase 6 needs three seed sets that never move: search may look at ``training``
as often as it likes, ``validation`` decides champion promotion, and ``holdout``
is untouched except for milestone reports. "Immutable" is enforced rather than
promised — the split files are checked in, this module regenerates them from a
fixed derivation, and ``verify`` fails if a checked-in file is not exactly what
the derivation produces.

Derivation (version ``v1``; changing any of it means a new version, not an edit):

* Each split has its own SHA-256 counter stream keyed by
  ``kaggriculture/seeds/v1/<split>/<counter>``.
* A candidate is the first 8 bytes of that digest, big-endian, mapped into
  ``[SEED_MIN, SEED_MAX]``.
* Splits are filled in the fixed order ``holdout``, ``validation``, ``training``,
  and a candidate already claimed by an earlier split (or by this split) is
  skipped. Filling in that order means growing ``training`` later cannot perturb
  the two sets that gate promotion.

``SEED_MIN`` is 1000 because seeds 0..89 are already the golden-vector and
benchmark development seeds; keeping evaluation seeds above them means a number
appearing in an evaluation artifact is never one a policy was debugged on.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

VERSION = "v1"
SEED_MIN = 1000
SEED_MAX = 2**31 - 2

# Ordered: earlier splits claim their seeds first (see the module docstring).
SPLITS: tuple[tuple[str, int], ...] = (
    ("holdout", 512),
    ("validation", 512),
    ("training", 1024),
)

SPLIT_DIR = Path(__file__).resolve().parent.parent / "experiments" / "seeds"

PURPOSE = {
    "training": "search and tuning; may be examined without limit",
    "validation": "champion promotion decisions only",
    "holdout": "milestone reports only; never used to choose anything",
}


def _candidate(split: str, counter: int) -> int:
    digest = hashlib.sha256(
        f"kaggriculture/seeds/{VERSION}/{split}/{counter}".encode()
    ).digest()
    span = SEED_MAX - SEED_MIN + 1
    return SEED_MIN + (int.from_bytes(digest[:8], "big") % span)


def derive() -> dict[str, list[int]]:
    """The whole derivation, as a pure function of the constants above."""
    claimed: set[int] = set()
    splits: dict[str, list[int]] = {}
    for split, size in SPLITS:
        seeds: list[int] = []
        counter = 0
        while len(seeds) < size:
            seed = _candidate(split, counter)
            counter += 1
            if seed in claimed:
                continue
            claimed.add(seed)
            seeds.append(seed)
        splits[split] = seeds
    return splits


def render(split: str, seeds: list[int]) -> str:
    header = [
        f"# Kaggriculture evaluation seeds: {split} ({VERSION})",
        f"# {PURPOSE[split]}",
        "# Generated by tools/seed_splits.py; do not edit by hand.",
        f"# {len(seeds)} seeds, disjoint from every other split.",
    ]
    return "\n".join(header + [str(seed) for seed in seeds]) + "\n"


def path_for(split: str) -> Path:
    return SPLIT_DIR / f"{split}.txt"


def load(split: str) -> list[int]:
    """Read a checked-in split. The reader every consumer should use."""
    seeds = []
    for line in path_for(split).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            seeds.append(int(line))
    return seeds


def write() -> None:
    SPLIT_DIR.mkdir(parents=True, exist_ok=True)
    for split, seeds in derive().items():
        path_for(split).write_text(render(split, seeds))
        print(f"wrote {path_for(split)} ({len(seeds)} seeds)")


def verify() -> int:
    derived = derive()
    failures = []
    for split, seeds in derived.items():
        path = path_for(split)
        if not path.exists():
            failures.append(f"{path} is missing")
            continue
        if path.read_text() != render(split, seeds):
            failures.append(f"{path} differs from the {VERSION} derivation")
    seen: dict[int, str] = {}
    for split, seeds in derived.items():
        if len(set(seeds)) != len(seeds):
            failures.append(f"{split} contains duplicates")
        for seed in seeds:
            if seed in seen:
                failures.append(f"seed {seed} is in both {seen[seed]} and {split}")
            seen[seed] = split
        for seed in seeds:
            if not SEED_MIN <= seed <= SEED_MAX:
                failures.append(f"seed {seed} in {split} is outside the drawn range")
    for failure in failures:
        print(f"FAIL {failure}", file=sys.stderr)
    if failures:
        return 1
    total = sum(len(seeds) for seeds in derived.values())
    print(f"OK {len(derived)} splits, {total} seeds, disjoint, matching {VERSION}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["write", "verify", "show"])
    parser.add_argument("--split", choices=[name for name, _ in SPLITS])
    args = parser.parse_args()
    if args.command == "write":
        write()
        return 0
    if args.command == "verify":
        return verify()
    for split, _ in SPLITS:
        if args.split in (None, split):
            print(f"{split}: {' '.join(str(s) for s in load(split)[:8])} ...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
